In [18]:
import pandas as pd
import numpy as np

In [19]:
# Steps:
# 1. load dataset (udf, udf1, udf2, udf3)
# 2. Rename dataset column
# 3. Merge/combine dataset into one
# 4. Clean data (NA, duplicate, convert, std column name, etc.)
# 5. Create clean data csv
# 5. Repeat for fake user dataset (fudf, fudf1, fudf2)

# Real Users Datasets

## Loading Datasets

In [20]:
# DF
# Load the dataset
rawudf = pd.read_csv("users.csv")

# Choose columns need
udf = rawudf[["name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
udf.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
udf

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\3964826594.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  udf.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,Davide Dellacasa,braddd,20370,5470,2385,Fri Apr 06 10:58:22 +0000 2007,Founder of http://www.screenweek.it & http://w...
1,Simone Economo,eKoeS,3131,506,381,Mon Apr 30 15:08:42 +0000 2007,BSc degree (cum laude) in Computer Engineering...
2,tacone,tacone_,4024,264,87,Tue May 01 11:53:40 +0000 2007,Cogito ergo bestemmio.
3,alesaura,alesstar,40586,640,622,Tue May 15 16:55:16 +0000 2007,"Se la vita ti dà sarde, scapocciale!"
4,Angelo,PerDiletto,2016,62,64,Sun May 13 19:52:00 +0000 2007,Je me souviens
...,...,...,...,...,...,...,...
1476,Frilaif Official,frilaif,49,208,124,Mon Jan 28 07:13:47 +0000 2013,Sex and Erotic Advisor. Sexual health is a sta...
1477,♔♥HeartsQueen♥♔,Stronzetta__,66,22,55,Thu Feb 07 07:27:08 +0000 2013,Se avessi seguito tutte le regole non sarei ma...
1478,angelagervasi,angelagervasi2,4,0,4,Mon Feb 11 14:50:19 +0000 2013,"mamma e giovane nonna,laureata,amante del teat..."
1479,Midnight,Movie1O,3,2,4,Sat Feb 23 17:46:55 +0000 2013,"If you don't shut your fucking mouth, I will k..."
1480,ʸᵒᵘ,xjawaadscookie,2568,351,341,Sat Feb 23 23:17:08 +0000 2013,@onedirection I JUST WANNA SAY A MASSIVE THANK...

In [21]:
# DF1
# Load the dataset
rawudf1 = pd.read_csv("users(1).csv")

# Choose columns need
udf1 = rawudf1[["name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
udf1.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
udf1

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\3963333847.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  udf1.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,TASUKU HAYAKAWA,0918Bask,2177,208,332,Tue Jun 11 11:20:35 +0000 2013,15years ago X.Lines24
1,ro_or,1120Roll,2660,330,485,Tue May 13 10:37:57 +0000 2014,保守見習い地元大好き人間。 経済学、電工、仏教を勉強中、ちなDeではいかんのか？ (*^◯^*)
2,bearclaw,14KBBrown,1254,166,177,Wed May 04 23:30:37 +0000 2011,Let me see what your best move is!
3,pocahontas farida,wadespeters,202968,2248,981,Fri Sep 17 14:02:10 +0000 2010,20. menna: #farida #nyc and the 80s actually y...
4,Ms Kathy,191a5bd05da04dc,82,21,79,Fri Feb 06 04:10:49 +0000 2015,Cosmetologist
...,...,...,...,...,...,...,...
3469,Alejandro,zombiemaster999,315,94,597,Wed Oct 20 11:42:54 +0000 2010,NaN
3470,Zubair Niazi Ⓜ️,zubairniaziPTI,4099,5378,1238,Fri Oct 24 10:30:53 +0000 2014,[ Member PTI SMT Official ] ( PTI District Pre...
3471,Zuhazuu,zuhazuu1,199,18,136,Fri Jan 16 09:59:43 +0000 2015,NaN
3472,zveljka,zveljka,2609,41,263,Mon Mar 08 14:00:26 +0000 2010,Whatever it is you're seeking won't come in th...
3473,// karime //,cypherjimin,20997,498,109,Tue Nov 25 18:22:32 +0000 2014,NOT a Jimin stan | #Taelyn | @flowerdaddies | ...

In [22]:
# DF2
# Load the dataset
rawudf2 = pd.read_csv("user(2).csv", engine="python", sep=",") #find a source for this code

# Choose columns need
udf2 = rawudf2[["name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
udf2.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
udf2

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\716262617.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  udf2.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,早川援,0918Bask,3431.0,286.0,441.0,2013-06-11 11:20:35,motorcycle.&car.
1,ローラー,1120Roll,6179.0,351.0,554.0,2014-05-13 10:37:57,ゴロゴロするのが大好きなちなDeです。政治思想は掻い摘み派です。メモ帳化中。無言フォロー失礼...
2,Kelsey Brown,keke_brooke,1874.0,241.0,197.0,2011-05-04 23:30:37,Future mall Santa
3,bio,pinkfunkys,263152.0,2164.0,947.0,2010-09-17 14:02:10,no longer here I'm @toujoursbeiles
4,Ms Kathy,191a5bd05da04dc,140.0,23.0,96.0,2015-02-06 04:10:49,Cosmetologist
...,...,...,...,...,...,...,...
5046,veronica inglese,vero22ingl,1128.0,1923.0,278.0,2012-12-19 11:20:51,Atleta C.S.Esercito Nike
5047,Il Rugno nel Pugno,ilrugnonelpugno,12.0,4.0,0.0,2013-01-16 21:40:14,L'alternativa vegetale al governo animale
5048,angelagervasi,angelagervasi2,26.0,3.0,29.0,2013-02-11 14:50:19,"mamma e giovane nonna,laureata,amante del teat..."
5049,Midnight,Nocturnorama,64.0,8.0,325.0,2013-02-23 17:46:55,I killed Paul Allen. And I liked it.
5050,val,fullyblank,18561.0,1175.0,1350.0,2013-02-23 23:17:08,meglio un passato di verdure che un futuro di ...

In [23]:
# DF 3
# Load the dataset
rawudf3 = pd.read_csv("insta_influencers.csv")

# Choose columns need
udf3 = rawudf3[["Account", "Username",  "Posts", "Followers", "Following"]]

# Replace column names
udf3.rename({'Account':'name', 'Username':'username', 'Posts':'num_posts', 'Followers':'followers_count', 'Following':'following_count'}, axis=1, inplace=True)

udf3

,name,username,num_posts,followers_count,following_count
0,Instagram,instagram,"8,366","700,614,770",219
1,Cristiano Ronaldo,cristiano,"4,020","672,183,865",629
2,Leo Messi,leomessi,"1,464","511,812,454",357
3,Selena Gomez,selenagomez,"2,157","415,333,733",362
4,Kylie,kyliejenner,"7,378","390,888,657",132
...,...,...,...,...,...
97,Vinicius Jr. ⚡️🇧🇷,vinijr,744,"59,147,982","1,176"
98,BLΛƆKPIИK,blackpinkofficial,"2,097","58,925,428",5
99,Chris Hemsworth,chrishemsworth,"1,287","58,868,057",756
100,Kriti Sanon 🦋,kritisanon,"2,756","58,666,681",422
101,Wardell Curry,stephencurry30,"1,522","58,286,885","1,252"

## Combine All Datasets

In [24]:
# Combine all real users profile datasets
udfs = [udf, udf1, udf2, udf3]
combined_df = pd.concat(udfs, ignore_index=True)

combined_df

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,Davide Dellacasa,braddd,20370,5470,2385,Fri Apr 06 10:58:22 +0000 2007,Founder of http://www.screenweek.it & http://w...
1,Simone Economo,eKoeS,3131,506,381,Mon Apr 30 15:08:42 +0000 2007,BSc degree (cum laude) in Computer Engineering...
2,tacone,tacone_,4024,264,87,Tue May 01 11:53:40 +0000 2007,Cogito ergo bestemmio.
3,alesaura,alesstar,40586,640,622,Tue May 15 16:55:16 +0000 2007,"Se la vita ti dà sarde, scapocciale!"
4,Angelo,PerDiletto,2016,62,64,Sun May 13 19:52:00 +0000 2007,Je me souviens
...,...,...,...,...,...,...,...
10103,Vinicius Jr. ⚡️🇧🇷,vinijr,744,"59,147,982","1,176",NaN,NaN
10104,BLΛƆKPIИK,blackpinkofficial,"2,097","58,925,428",5,NaN,NaN
10105,Chris Hemsworth,chrishemsworth,"1,287","58,868,057",756,NaN,NaN
10106,Kriti Sanon 🦋,kritisanon,"2,756","58,666,681",422,NaN,NaN
10107,Wardell Curry,stephencurry30,"1,522","58,286,885","1,252",NaN,NaN

## Additional Columns

In [25]:
# Create additional columns 
# id
combined_df['id'] = range(1, 1 + len(combined_df)) 

# Bio length
combined_df['bio_length'] = combined_df['bio'].str.len().fillna(-1).astype(int)      # -1 represent if bio unknown

# Number of digit in Username
combined_df['num_digits_username'] = combined_df['username'].str.count(r'\d').fillna(0).astype(int)

# Username_length
combined_df['username_length'] = combined_df['username'].str.len().fillna(-1).astype(int)
# Digit & Uername Ratio
combined_df['digit_ratio_username'] = combined_df['num_digits_username'] / combined_df['username_length'] 
combined_df['digit_ratio_username'] = combined_df['digit_ratio_username'].replace([np.inf, -np.inf], -1).fillna(-1)

# Real accounts
combined_df['fake'] = 0

# Followers & Following ratio
combined_df["followers_count"] = pd.to_numeric(combined_df["followers_count"], errors="coerce").fillna(-1).astype(int)
combined_df["following_count"] = pd.to_numeric(combined_df["following_count"], errors="coerce").fillna(-1).astype(int)
combined_df['followers_following_ratio'] = np.select(
    [
        (combined_df['followers_count'] == -1) | (combined_df['following_count'] == -1),      # Condition unknown
        (combined_df['followers_count'] == 0) | (combined_df['following_count'] == 0)     # Condition 0
    ],
    [
        -1,         # result  if following/followers is unknown, set -1
        0           # result  if following/followers is 0, set 0
    ],
    default=combined_df['followers_count'] / combined_df['following_count']
) 
combined_df['followers_following_ratio'] = combined_df['followers_following_ratio'].round(2)       # round result

# Reorder columns
combined_df = combined_df[['id', 'username', 'name', 'account_created_at', 
                           'bio', 'bio_length', 'num_posts', 'followers_count', 
                           'following_count', 'username_length', 'num_digits_username',
                           'digit_ratio_username', 'followers_following_ratio', 'fake']]

combined_df

,id,username,name,account_created_at,bio,bio_length,num_posts,followers_count,following_count,username_length,num_digits_username,digit_ratio_username,followers_following_ratio,fake
0,1,braddd,Davide Dellacasa,Fri Apr 06 10:58:22 +0000 2007,Founder of http://www.screenweek.it & http://w...,151,20370,5470,2385,6,0,0.000000,2.29,0
1,2,eKoeS,Simone Economo,Mon Apr 30 15:08:42 +0000 2007,BSc degree (cum laude) in Computer Engineering...,104,3131,506,381,5,0,0.000000,1.33,0
2,3,tacone_,tacone,Tue May 01 11:53:40 +0000 2007,Cogito ergo bestemmio.,22,4024,264,87,7,0,0.000000,3.03,0
3,4,alesstar,alesaura,Tue May 15 16:55:16 +0000 2007,"Se la vita ti dà sarde, scapocciale!",36,40586,640,622,8,0,0.000000,1.03,0
4,5,PerDiletto,Angelo,Sun May 13 19:52:00 +0000 2007,Je me souviens,14,2016,62,64,10,0,0.000000,0.97,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,10104,vinijr,Vinicius Jr. ⚡️🇧🇷,NaN,NaN,-1,744,-1,-1,6,0,0.000000,-1.00,0
10104,10105,blackpinkofficial,BLΛƆKPIИK,NaN,NaN,-1,"2,097",-1,5,17,0,0.000000,-1.00,0
10105,10106,chrishemsworth,Chris Hemsworth,NaN,NaN,-1,"1,287",-1,756,14,0,0.000000,-1.00,0
10106,10107,kritisanon,Kriti Sanon 🦋,NaN,NaN,-1,"2,756",-1,422,10,0,0.000000,-1.00,0
10107,10108,stephencurry30,Wardell Curry,NaN,NaN,-1,"1,522",-1,-1,14,2,0.142857,-1.00,0

## Cleaned Datasets

In [26]:
# Get dataset information
print(combined_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         10108 non-null  int64
 1   username                   10107 non-null  object
 2   name                       10106 non-null  object
 3   account_created_at         9995 non-null   object
 4   bio                        9040 non-null   object
 5   bio_length                 10108 non-null  int64
 6   num_posts                  10102 non-null  object
 7   followers_count            10108 non-null  int64
 8   following_count            10108 non-null  int64
 9   username_length            10108 non-null  int64
 10  num_digits_username        10108 non-null  int64
 11  digit_ratio_username       10108 non-null  float64
 12  followers_following_ratio  10108 non-null  float64
 13  fake                       10108 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.1+ MB
None

In [27]:
# Check if numeric & text for the column
print(combined_df.dtypes)

id                             int64
username                      object
name                          object
account_created_at            object
bio                           object
bio_length                     int64
num_posts                     object
followers_count                int64
following_count                int64
username_length                int64
num_digits_username            int64
digit_ratio_username         float64
followers_following_ratio    float64
fake                           int64
dtype: object

In [28]:
# conver column elements to numberic


combined_df["num_posts"] = pd.to_numeric(combined_df["num_posts"], errors="coerce").fillna(-1).astype(int)

# Convert "created_at" to datetime
combined_df["account_created_at"] = pd.to_datetime(combined_df["account_created_at"], errors="coerce")

print("\nUpdated Data Types:")
print(combined_df.dtypes)

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\643246983.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_df["account_created_at"] = pd.to_datetime(combined_df["account_created_at"], errors="coerce")

Updated Data Types:
id                             int64
username                      object
name                          object
account_created_at            object
bio                           object
bio_length                     int64
num_posts                      int64
followers_count                int64
following_count                int64
username_length                int64
num_digits_username            int64
digit_ratio_username         float64
followers_following_ratio    float64
fake                           int64
dtype: object

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\643246983.py:7: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  combined_df["account_created_at"] = pd.to_datetime(combined_df["account_created_at"], errors="coerce")

In [29]:
# Check for any missing values
print(combined_df.isnull().sum())

id                              0
username                        1
name                            2
account_created_at            113
bio                          1068
bio_length                      0
num_posts                       0
followers_count                 0
following_count                 0
username_length                 0
num_digits_username             0
digit_ratio_username            0
followers_following_ratio       0
fake                            0
dtype: int64

In [30]:
# Fill missing values
combined_df["name"] = combined_df["name"].fillna("NA")
combined_df["username"] = combined_df["username"].fillna("NA")
combined_df["num_posts"] = combined_df["num_posts"].fillna(-1)

combined_df["account_created_at"] = combined_df["account_created_at"].fillna(-1)
combined_df["bio"] = combined_df["bio"].fillna("NA")

# Verify missing values are handled
print(combined_df.isnull().sum())

id                           0
username                     0
name                         0
account_created_at           0
bio                          0
bio_length                   0
num_posts                    0
followers_count              0
following_count              0
username_length              0
num_digits_username          0
digit_ratio_username         0
followers_following_ratio    0
fake                         0
dtype: int64

In [31]:
# Check Duplicate
duplicates = combined_df.duplicated().sum()
print(f"\nOriginal Number of Duplicates:{duplicates}")

# Remove Duplicate
combined_df = combined_df.drop_duplicates()

# Verify duplicates are removed
print(f"Number of of Duplicates Remaining: {combined_df.duplicated().sum()}")

Original Number of Duplicates:0
Number of of Duplicates Remaining: 0

In [32]:
combined_df

,id,username,name,account_created_at,bio,bio_length,num_posts,followers_count,following_count,username_length,num_digits_username,digit_ratio_username,followers_following_ratio,fake
0,1,braddd,Davide Dellacasa,2007-04-06 10:58:22+00:00,Founder of http://www.screenweek.it & http://w...,151,20370,5470,2385,6,0,0.000000,2.29,0
1,2,eKoeS,Simone Economo,2007-04-30 15:08:42+00:00,BSc degree (cum laude) in Computer Engineering...,104,3131,506,381,5,0,0.000000,1.33,0
2,3,tacone_,tacone,2007-05-01 11:53:40+00:00,Cogito ergo bestemmio.,22,4024,264,87,7,0,0.000000,3.03,0
3,4,alesstar,alesaura,2007-05-15 16:55:16+00:00,"Se la vita ti dà sarde, scapocciale!",36,40586,640,622,8,0,0.000000,1.03,0
4,5,PerDiletto,Angelo,2007-05-13 19:52:00+00:00,Je me souviens,14,2016,62,64,10,0,0.000000,0.97,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,10104,vinijr,Vinicius Jr. ⚡️🇧🇷,-1,NA,-1,744,-1,-1,6,0,0.000000,-1.00,0
10104,10105,blackpinkofficial,BLΛƆKPIИK,-1,NA,-1,-1,-1,5,17,0,0.000000,-1.00,0
10105,10106,chrishemsworth,Chris Hemsworth,-1,NA,-1,-1,-1,756,14,0,0.000000,-1.00,0
10106,10107,kritisanon,Kriti Sanon 🦋,-1,NA,-1,-1,-1,422,10,0,0.000000,-1.00,0
10107,10108,stephencurry30,Wardell Curry,-1,NA,-1,-1,-1,-1,14,2,0.142857,-1.00,0

## Convert To CSV

In [33]:
# Save all cleaned datasets
Cleaned_file_path = "user_cleaned_dataset.csv"
combined_df.to_csv(Cleaned_file_path, index=False)

print(f"\nCleaned dataset saved to: {Cleaned_file_path}")

Cleaned dataset saved to: user_cleaned_dataset.csv

# Fake Users Datasets

## Loading Datasets

In [47]:
# DF
# Load the dataset
rawfudf = pd.read_csv("fusers.csv")

# Choose columns need
fudf = rawfudf[["name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
fudf.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
fudf

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\1508247228.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fudf.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,pirfectmoses,pirfectmoses,24,4,588,Thu Sep 08 13:20:35 +0000 2011,NaN
1,SAK Nair,bsknair1967,656,57,693,Sun May 03 07:35:13 +0000 2009,in Kuwait with my buetiful family.
2,Deepak,dedjven,1234,15,104,Sun Sep 06 19:50:08 +0000 2009,NaN
3,Marcos Vinicius,BrowAlves,573,14,227,Fri Oct 16 14:02:48 +0000 2009,NaN
4,Shri Kant Kanaujia,kanaujiask,675,18,519,Sun Jan 31 12:08:41 +0000 2010,NaN
...,...,...,...,...,...,...,...
1332,Verda Marks,VerdaMarks1,1,0,17,Tue Apr 30 08:23:57 +0000 2013,I have been in business onlin and offline for ...
1333,Danial Campbell,DanialCampbell2,0,1,17,Tue Apr 30 08:34:49 +0000 2013,NaN
1334,Maudie Meyer,MaudieMeyer1,2,0,15,Tue Apr 30 09:21:12 +0000 2013,NaN
1335,Harriett Harvey,HarriettHarvey9,2,0,16,Tue Apr 30 11:25:11 +0000 2013,NaN
1336,Gillian Wheeler,GillianWheeler3,0,0,17,Tue Apr 30 12:47:51 +0000 2013,Hello!im a BELIEBER! IM A HUGE FAN OF JUSTIN B...

In [48]:
# DF1
# Load the dataset
rawfudf1 = pd.read_csv("fusers(1).csv")

# Choose columns need
fudf1 = rawfudf1[["name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
fudf1.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
fudf1

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\4286554321.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fudf1.rename({'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,YI YUAN,yi_twitts,29,19,255,Wed Oct 07 03:19:21 +0000 2009,real estate sales
1,Marcos Perez C,marcos_peca,1408,208,866,Wed Oct 14 23:40:17 +0000 2009,NaN
2,curti lorenzo,curtilorenzo,39,59,962,Sun Jan 17 16:46:52 +0000 2010,le corna del capro scappato dal gregge s'infil...
3,ruben dario toscano,gatito2710,59,7,49,Mon Feb 15 15:49:58 +0000 2010,NaN
4,Malek Khalaf,MalekKhalaf,987,60,521,Mon Mar 15 11:38:55 +0000 2010,"MA student at JU, Interested in Juventus,Italy..."
...,...,...,...,...,...,...,...
3346,Verda Marks,VerdaMarks1,1,0,17,Tue Apr 30 08:23:57 +0000 2013,I have been in business onlin and offline for ...
3347,Danial Campbell,DanialCampbell2,0,1,17,Tue Apr 30 08:34:49 +0000 2013,NaN
3348,Maudie Meyer,MaudieMeyer1,2,0,15,Tue Apr 30 09:21:12 +0000 2013,NaN
3349,Harriett Harvey,HarriettHarvey9,2,0,16,Tue Apr 30 11:25:11 +0000 2013,NaN
3350,Gillian Wheeler,GillianWheeler3,0,0,17,Tue Apr 30 12:47:51 +0000 2013,Hello!im a BELIEBER! IM A HUGE FAN OF JUSTIN B...

In [49]:
# DF2
# Load the dataset
rawfudf2 = pd.read_csv("fusers(2).csv", engine='python', on_bad_lines='warn')     # Switch to Python engine to skip/warn about bad rows


# Choose columns need
fudf2 = rawfudf2[["user_name", "screen_name", "statuses_count", "followers_count", "friends_count", "created_at", "description"]]

# Replace column names
fudf2.rename({'user_name':'name', 'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)
fudf2

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\2138371457.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fudf2.rename({'user_name':'name', 'screen_name':'username', 'statuses_count':'num_posts', 'friends_count':'following_count', 'created_at':'account_created_at', 'description':'bio'}, axis=1, inplace=True)

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,Allen,pxibejs_pgv,1272.0,28.0,1658.0,2013-07-22 10:05:39,Husband. Dad. Salesman. Learner. Out-of-the-b...
1,Shawn,8VD6Y,9.0,19.0,380.0,2013-12-17 12:32:16,"Guitarist, Vengeance You!!!"
2,Jeffrey A.,jefygfr,24.0,28.0,723.0,2013-12-12 13:29:44,"President, American Birding Association. \r\n..."
3,Toxic,Toxicghts1o9,2624.0,36.0,640.0,2014-03-22 21:06:48,"19, Gamer, Drummer - Just do what the makes..."
4,Total,TotalHighspede,377.0,18.0,838.0,2015-06-28 10:36:11,Total Highspeed specializes in business and re...
...,...,...,...,...,...,...,...
2646,Byron Ma,byroamnh,107.0,13.0,1482.0,2014-04-14 15:06:29,"Tech , music and lover. Leading publishing ..."
2647,Barb,northwindsavhc,2369.0,40.0,967.0,2015-05-02 13:09:37,"North Winds Heating & , Inc. has provided prec..."
2648,The Space of,Since_Thereoerf,11.0,19.0,447.0,2014-05-10 01:54:51,"Stand-Up Philosopher, Author, Writer, , Artist..."
2649,Shop,TheSOILSotre,0.0,9.0,680.0,2015-06-12 15:33:30,We are your #1 choice for all your landscaping...
2650,Tyler,IARETYRWAR,501.0,9.0,579.0,2014-03-12 07:54:15,me makey musics for earhoels. Go out my stuff...

## Combine All Datasets

In [50]:
# Combine all real users profile datasets
fudfs = [fudf, fudf1, fudf2]
combined_fdf = pd.concat(fudfs, ignore_index=True)

combined_fdf

,name,username,num_posts,followers_count,following_count,account_created_at,bio
0,pirfectmoses,pirfectmoses,24.0,4.0,588.0,Thu Sep 08 13:20:35 +0000 2011,NaN
1,SAK Nair,bsknair1967,656.0,57.0,693.0,Sun May 03 07:35:13 +0000 2009,in Kuwait with my buetiful family.
2,Deepak,dedjven,1234.0,15.0,104.0,Sun Sep 06 19:50:08 +0000 2009,NaN
3,Marcos Vinicius,BrowAlves,573.0,14.0,227.0,Fri Oct 16 14:02:48 +0000 2009,NaN
4,Shri Kant Kanaujia,kanaujiask,675.0,18.0,519.0,Sun Jan 31 12:08:41 +0000 2010,NaN
...,...,...,...,...,...,...,...
7334,Byron Ma,byroamnh,107.0,13.0,1482.0,2014-04-14 15:06:29,"Tech , music and lover. Leading publishing ..."
7335,Barb,northwindsavhc,2369.0,40.0,967.0,2015-05-02 13:09:37,"North Winds Heating & , Inc. has provided prec..."
7336,The Space of,Since_Thereoerf,11.0,19.0,447.0,2014-05-10 01:54:51,"Stand-Up Philosopher, Author, Writer, , Artist..."
7337,Shop,TheSOILSotre,0.0,9.0,680.0,2015-06-12 15:33:30,We are your #1 choice for all your landscaping...
7338,Tyler,IARETYRWAR,501.0,9.0,579.0,2014-03-12 07:54:15,me makey musics for earhoels. Go out my stuff...

## Additional Columns

In [51]:
# Create additional columns 
# id
combined_fdf['id'] = range(1, 1 + len(combined_fdf)) 

# Bio length
combined_fdf['bio_length'] = combined_fdf['bio'].str.len().fillna(-1).astype(int)      # -1 represent if bio unknown

# Number of digit in Username
combined_fdf['num_digits_username'] = combined_fdf['username'].str.count(r'\d').fillna(0).astype(int)

# Username_length
combined_fdf['username_length'] = combined_fdf['username'].str.len().fillna(-1).astype(int)
# Digit & Uername Ratio
combined_fdf['digit_ratio_username'] = combined_fdf['num_digits_username'] / combined_fdf['username_length'] 
combined_fdf['digit_ratio_username'] = combined_fdf['digit_ratio_username'].replace([np.inf, -np.inf], -1).fillna(-1)

# Real accounts
combined_fdf['fake'] = 1

# Followers & Following ratio
combined_fdf["followers_count"] = pd.to_numeric(combined_fdf["followers_count"], errors="coerce").fillna(-1).astype(int)
combined_fdf["following_count"] = pd.to_numeric(combined_fdf["following_count"], errors="coerce").fillna(-1).astype(int)
combined_fdf['followers_following_ratio'] = np.select(
    [
        (combined_fdf['followers_count'] == -1) | (combined_fdf['following_count'] == -1),      # Condition unknown
        (combined_fdf['followers_count'] == 0) | (combined_fdf['following_count'] == 0)     # Condition 0
    ],
    [
        -1,         # result  if following/followers is unknown, set -1
        0           # result  if following/followers is 0, set 0
    ],
    default=combined_fdf['followers_count'] / combined_fdf['following_count']
) 
combined_fdf['followers_following_ratio'] = combined_fdf['followers_following_ratio'].round(2)       # round result

# Reorder columns
combined_fdf = combined_fdf[['id', 'username', 'name', 'account_created_at', 
                           'bio', 'bio_length', 'num_posts', 'followers_count', 
                           'following_count', 'username_length', 'num_digits_username',
                           'digit_ratio_username', 'followers_following_ratio', 'fake']]

combined_fdf

,id,username,name,account_created_at,bio,bio_length,num_posts,followers_count,following_count,username_length,num_digits_username,digit_ratio_username,followers_following_ratio,fake
0,1,pirfectmoses,pirfectmoses,Thu Sep 08 13:20:35 +0000 2011,NaN,-1,24.0,4,588,12,0,0.000000,0.01,1
1,2,bsknair1967,SAK Nair,Sun May 03 07:35:13 +0000 2009,in Kuwait with my buetiful family.,34,656.0,57,693,11,4,0.363636,0.08,1
2,3,dedjven,Deepak,Sun Sep 06 19:50:08 +0000 2009,NaN,-1,1234.0,15,104,7,0,0.000000,0.14,1
3,4,BrowAlves,Marcos Vinicius,Fri Oct 16 14:02:48 +0000 2009,NaN,-1,573.0,14,227,9,0,0.000000,0.06,1
4,5,kanaujiask,Shri Kant Kanaujia,Sun Jan 31 12:08:41 +0000 2010,NaN,-1,675.0,18,519,10,0,0.000000,0.03,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,7335,byroamnh,Byron Ma,2014-04-14 15:06:29,"Tech , music and lover. Leading publishing ...",96,107.0,13,1482,8,0,0.000000,0.01,1
7335,7336,northwindsavhc,Barb,2015-05-02 13:09:37,"North Winds Heating & , Inc. has provided prec...",127,2369.0,40,967,14,0,0.000000,0.04,1
7336,7337,Since_Thereoerf,The Space of,2014-05-10 01:54:51,"Stand-Up Philosopher, Author, Writer, , Artist...",87,11.0,19,447,15,0,0.000000,0.04,1
7337,7338,TheSOILSotre,Shop,2015-06-12 15:33:30,We are your #1 choice for all your landscaping...,113,0.0,9,680,12,0,0.000000,0.01,1
7338,7339,IARETYRWAR,Tyler,2014-03-12 07:54:15,me makey musics for earhoels. Go out my stuff...,104,501.0,9,579,10,0,0.000000,0.02,1

## Cleaned Fake Datasets

In [52]:
# Get dataset information
print(combined_fdf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7339 entries, 0 to 7338
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         7339 non-null   int64
 1   username                   7339 non-null   object
 2   name                       7339 non-null   object
 3   account_created_at         7337 non-null   object
 4   bio                        5965 non-null   object
 5   bio_length                 7339 non-null   int64
 6   num_posts                  7338 non-null   float64
 7   followers_count            7339 non-null   int64
 8   following_count            7339 non-null   int64
 9   username_length            7339 non-null   int64
 10  num_digits_username        7339 non-null   int64
 11  digit_ratio_username       7339 non-null   float64
 12  followers_following_ratio  7339 non-null   float64
 13  fake                       7339 non-null   int64
dtypes: float64(3), int64(7), object(4)
memory usage: 802.8+ KB
None

In [53]:
# Check if numeric & text for the column
print(combined_fdf.dtypes)

id                             int64
username                      object
name                          object
account_created_at            object
bio                           object
bio_length                     int64
num_posts                    float64
followers_count                int64
following_count                int64
username_length                int64
num_digits_username            int64
digit_ratio_username         float64
followers_following_ratio    float64
fake                           int64
dtype: object

In [54]:
# conver column elements to numberic


combined_fdf["num_posts"] = pd.to_numeric(combined_fdf["num_posts"], errors="coerce").fillna(-1).astype(int)

# Convert "created_at" to datetime
combined_fdf["account_created_at"] = pd.to_datetime(combined_fdf["account_created_at"], errors="coerce")

print("\nUpdated Data Types:")
print(combined_fdf.dtypes)

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\4016442359.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_fdf["account_created_at"] = pd.to_datetime(combined_fdf["account_created_at"], errors="coerce")

Updated Data Types:
id                             int64
username                      object
name                          object
account_created_at            object
bio                           object
bio_length                     int64
num_posts                      int64
followers_count                int64
following_count                int64
username_length                int64
num_digits_username            int64
digit_ratio_username         float64
followers_following_ratio    float64
fake                           int64
dtype: object

C:\Users\phuon\AppData\Local\Temp\ipykernel_9156\4016442359.py:7: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  combined_fdf["account_created_at"] = pd.to_datetime(combined_fdf["account_created_at"], errors="coerce")

In [55]:
# Check for any missing values
print(combined_fdf.isnull().sum())

id                              0
username                        0
name                            0
account_created_at              2
bio                          1374
bio_length                      0
num_posts                       0
followers_count                 0
following_count                 0
username_length                 0
num_digits_username             0
digit_ratio_username            0
followers_following_ratio       0
fake                            0
dtype: int64

In [56]:
# Fill missing values
combined_fdf["name"] = combined_fdf["name"].fillna("NA")
combined_fdf["username"] = combined_fdf["username"].fillna("NA")
combined_fdf["num_posts"] = combined_fdf["num_posts"].fillna(-1)

combined_fdf["account_created_at"] = combined_fdf["account_created_at"].fillna(-1)
combined_fdf["bio"] = combined_fdf["bio"].fillna("NA")

# Verify missing values are handled
print(combined_fdf.isnull().sum())

id                           0
username                     0
name                         0
account_created_at           0
bio                          0
bio_length                   0
num_posts                    0
followers_count              0
following_count              0
username_length              0
num_digits_username          0
digit_ratio_username         0
followers_following_ratio    0
fake                         0
dtype: int64

In [57]:
# Check Duplicate 
print(f"\nOriginal Number of Duplicates:{combined_fdf.duplicated().sum()}")

# Remove Duplicate
combined_fdf = combined_fdf.drop_duplicates()

# Verify duplicates are removed
print(f"Number of of Duplicates Remaining: {combined_fdf.duplicated().sum()}")

Original Number of Duplicates:0
Number of of Duplicates Remaining: 0

In [58]:
combined_fdf

,id,username,name,account_created_at,bio,bio_length,num_posts,followers_count,following_count,username_length,num_digits_username,digit_ratio_username,followers_following_ratio,fake
0,1,pirfectmoses,pirfectmoses,2011-09-08 13:20:35+00:00,NA,-1,24,4,588,12,0,0.000000,0.01,1
1,2,bsknair1967,SAK Nair,2009-05-03 07:35:13+00:00,in Kuwait with my buetiful family.,34,656,57,693,11,4,0.363636,0.08,1
2,3,dedjven,Deepak,2009-09-06 19:50:08+00:00,NA,-1,1234,15,104,7,0,0.000000,0.14,1
3,4,BrowAlves,Marcos Vinicius,2009-10-16 14:02:48+00:00,NA,-1,573,14,227,9,0,0.000000,0.06,1
4,5,kanaujiask,Shri Kant Kanaujia,2010-01-31 12:08:41+00:00,NA,-1,675,18,519,10,0,0.000000,0.03,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,7335,byroamnh,Byron Ma,2014-04-14 15:06:29,"Tech , music and lover. Leading publishing ...",96,107,13,1482,8,0,0.000000,0.01,1
7335,7336,northwindsavhc,Barb,2015-05-02 13:09:37,"North Winds Heating & , Inc. has provided prec...",127,2369,40,967,14,0,0.000000,0.04,1
7336,7337,Since_Thereoerf,The Space of,2014-05-10 01:54:51,"Stand-Up Philosopher, Author, Writer, , Artist...",87,11,19,447,15,0,0.000000,0.04,1
7337,7338,TheSOILSotre,Shop,2015-06-12 15:33:30,We are your #1 choice for all your landscaping...,113,0,9,680,12,0,0.000000,0.01,1
7338,7339,IARETYRWAR,Tyler,2014-03-12 07:54:15,me makey musics for earhoels. Go out my stuff...,104,501,9,579,10,0,0.000000,0.02,1

## Convert To CSV

In [60]:
# Save all cleaned datasets
Cleaned_file_path = "fuser_cleaned_dataset.csv"
combined_fdf.to_csv(Cleaned_file_path, index=False)

print(f"\nCleaned dataset saved to: {Cleaned_file_path}")

Cleaned dataset saved to: fuser_cleaned_dataset.csv